### ISSUE TITLE
Farklı boyutlar için ayar

### ISSUE THREAD

**Issue by talhakeskin** [EPSGrup13/EPS#18]
gizlilik-politikasi.html'in farklı boyutlar için düzenlenmesi gerekiyor,
mevcut durumda sadece 1920x1080'de düzgün görünmekte.

Edit;
width normal css ve media için % olarak düzeltilmesi gerek,
üst-alt ortalanması lazım

**Comment by anilcanboga** [comment]
Responsive tasarım güncellendi.
