### ISSUE TITLE
Boyut ayarları

### ISSUE THREAD

**Issue by talhakeskin** [EPSGrup13/EPS#44]
1) Firefox için "Yorumlar ve Puanlar" hover yapıldığında minimum olarak width: 159px gerektiriyor.
~~2) parkPageBox div'i min-height: calc(100% - 96px); gerektiriyor.~~ tarafımca düzeltildi

1 - 
![1-1](https://user-images.githubusercontent.com/50806631/79741158-763ee880-8309-11ea-8d6f-de73d335ef9c.png)
~~2~~
![1-2](https://user-images.githubusercontent.com/50806631/79741168-79d26f80-8309-11ea-9664-b85281a974e2.png)

**Comment by talhakeskin** [comment]
#43

**Comment by mervemor** [comment]
Bir önceki güncellemede düzenleme sağlandı.
